### ISSUE TITLE
Depth testing on only one layer

### ISSUE THREAD

**Issue by mashlol** [Arvtesh/UnityFx.Outline#18]
Is it possible to do depth testing on one layer only? For example, I want the outlines to show through every layer except "Ground". So if the object is behind a tree or something, it will show through, but if it is behind a mountain, it wouldn't.

**Comment by Arvtesh** [comment]
Hmm, right now it's not supported via high-level API like `OutlineBehaviour`. But you should be able to achive that using `OutlineRenderer`. In theory all you need is custom depth map, that includes only data from desired set of objects. Once you have it, use it with `OutlineRenderer` instead of the built-in depth. Usage patterns differ depending on render pipeline used, but it should look like:
`using (var renderer = new OutlineRenderer(commandBuffer, resources, renderTarget, depthTexture, renderTargetDesc))
{
  renderer.Render(renderers, outlineSettings);
}`
